apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  updateStrategy:
    type: InPlace
  values:
    global:
      meshID: mesh2
      multiCluster:
        clusterName: cluster2
      network: network2
    meshConfig:
      extensionProviders:
      - name: otel
        opentelemetry:
          port: 4317
          service: otel-collector.opentelemetrycollector.svc.cluster.local
  version: v1.24.3
